# This rule is not used by the project heliop itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the authelia.snosr.se.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: heliop
    app.kubernetes.io/managed-by: kustomize
  name: autheliaoauthclient-editor-role
rules:
- apiGroups:
  - authelia.snosr.se
  resources:
  - autheliaoauthclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authelia.snosr.se
  resources:
  - autheliaoauthclients/status
  verbs:
  - get
