## Append samples of your project ##
resources:
- authelia_v1alpha1_authelia.yaml
- authelia_v1alpha1_autheliaoauthclient.yaml
- networking_v1_ingress.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
