/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AutheliaSpec defines the desired state of Authelia
type AutheliaSpec struct {
	// deployment configures the Authelia Deployment generated by the operator.
	// +optional
	Deployment AutheliaDeploymentSpec `json:"deployment,omitempty"`

	// config is the Authelia configuration.yaml content. The operator injects
	// OIDC clients defined via AutheliaOAuthClient resources into
	// identity_providers.oidc.clients before rendering it into a ConfigMap.
	// +required
	Config string `json:"config"`
}

// AutheliaDeploymentSpec configures the generated Authelia Deployment.
type AutheliaDeploymentSpec struct {
	// replicas is the number of Authelia pods to run.
	// +optional
	// +kubebuilder:default=2
	Replicas *int32 `json:"replicas,omitempty"`

	// image is the Authelia container image.
	// +optional
	// +kubebuilder:default="ghcr.io/authelia/authelia:4"
	Image string `json:"image,omitempty"`

	// imagePullPolicy is the image pull policy for the Authelia container.
	// +optional
	// +kubebuilder:default="IfNotPresent"
	ImagePullPolicy corev1.PullPolicy `json:"imagePullPolicy,omitempty"`

	// resources describes the compute resource requirements for the Authelia
	// container.
	// +optional
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// secretName is the Secret providing Authelia's core secrets. It is exposed
	// to the container via envFrom and mounted at /secrets.
	// +optional
	// +kubebuilder:default="authelia"
	SecretName string `json:"secretName,omitempty"`

	// postgresSecretName is the Secret mounted at /pg-secret providing the
	// PostgreSQL password (key: password).
	// +optional
	// +kubebuilder:default="authelia-db-app"
	PostgresSecretName string `json:"postgresSecretName,omitempty"`

	// redisSecretName is the Secret mounted at /redis-secret providing the
	// Redis password (key: redis-password).
	// +optional
	// +kubebuilder:default="redis-ha"
	RedisSecretName string `json:"redisSecretName,omitempty"`
}

// AutheliaStatus defines the observed state of Authelia.
type AutheliaStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// For Kubernetes API conventions, see:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

	// conditions represent the current state of the Authelia resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// readyReplicas is the number of ready Authelia pods.
	// +optional
	ReadyReplicas int32 `json:"readyReplicas,omitempty"`

	// oidcClients lists the OIDC client IDs currently rendered into the
	// Authelia configuration.
	// +optional
	OIDCClients []string `json:"oidcClients,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=authelias,singular=authelia
// +kubebuilder:printcolumn:name="Replicas",type="integer",JSONPath=".spec.deployment.replicas"
// +kubebuilder:printcolumn:name="Ready",type="integer",JSONPath=".status.readyReplicas"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// Authelia is the Schema for the authelia API
type Authelia struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of Authelia
	// +required
	Spec AutheliaSpec `json:"spec"`

	// status defines the observed state of Authelia
	// +optional
	Status AutheliaStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// AutheliaList contains a list of Authelia
type AutheliaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []Authelia `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Authelia{}, &AutheliaList{})
}
