/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// AutheliaSpec defines the desired state of Authelia
// +kubebuilder:validation:XValidation:rule="!has(self.traefik) || has(self.hostname)",message="hostname is required when traefik is set"
type AutheliaSpec struct {
	// hostname is the fully qualified hostname where the Authelia portal is
	// served (e.g. auth.example.com). It is used to generate a default session
	// cookie (authelia_url https://<hostname>, cookie domain the parent domain)
	// and as the Traefik IngressRoute host.
	// +optional
	Hostname string `json:"hostname,omitempty"`

	// deployment configures the Authelia Deployment generated by the operator.
	// +optional
	Deployment AutheliaDeploymentSpec `json:"deployment,omitempty"`

	// traefik, when set, makes the operator generate a Traefik IngressRoute for
	// the portal (at hostname) and a forwardAuth Middleware named
	// "<name>-forwardauth" that other IngressRoutes can reference to require
	// authentication. Requires the Traefik CRDs and hostname to be set.
	// +optional
	Traefik *TraefikSpec `json:"traefik,omitempty"`

	// settings holds the Authelia configuration and the Secret references the
	// operator wires into it.
	// +required
	Settings AutheliaSettings `json:"settings"`
}

// SecretKeyRef references a single key within a Secret in the Authelia's
// namespace.
type SecretKeyRef struct {
	// name is the name of the Secret.
	// +required
	Name string `json:"name"`

	// key is the key within the Secret.
	// +required
	Key string `json:"key"`
}

// AutheliaSettings holds the Authelia configuration (as a verbatim object) plus
// the Secret references the operator mounts and wires into that configuration.
type AutheliaSettings struct {
	// additionalConfig is the Authelia configuration (session,
	// authentication_backend, access_control, storage, notifier,
	// identity_providers, etc.) merged verbatim as the base configuration. The
	// operator layers on top: OIDC clients from AutheliaOAuthClient resources, a
	// default session cookie derived from hostname when none is set,
	// authentication_backend.file.path from fileUsersSecret, and removal of any
	// ldap password (supplied via the environment instead).
	// +optional
	AdditionalConfig *runtime.RawExtension `json:"additionalConfig,omitempty"`

	// fileUsersSecret, when set, mounts the file backend users database Secret
	// into the container and sets authentication_backend.file.path to the mounted
	// path.
	// +optional
	FileUsersSecret *SecretKeyRef `json:"fileUsersSecret,omitempty"`

	// secrets references Secrets that Authelia loads from files. Each entry is
	// mounted and exposed via the matching AUTHELIA_*_FILE environment variable.
	// +optional
	Secrets *AutheliaSecrets `json:"secrets,omitempty"`
}

// AutheliaSecrets references the Secrets that Authelia loads from files. Each
// field is named by the last two levels of the corresponding configuration key
// and maps to its AUTHELIA_*_FILE environment variable. See
// https://www.authelia.com/configuration/methods/secrets/
type AutheliaSecrets struct {
	// ldapPassword -> authentication_backend.ldap.password. When set, the
	// operator also removes any ldap password present in additionalConfig.
	// +optional
	LDAPPassword *SecretKeyRef `json:"ldapPassword,omitempty"`

	// smtpPassword -> notifier.smtp.password.
	// +optional
	SMTPPassword *SecretKeyRef `json:"smtpPassword,omitempty"`

	// redisPassword -> session.redis.password.
	// +optional
	RedisPassword *SecretKeyRef `json:"redisPassword,omitempty"`

	// postgresPassword -> storage.postgres.password.
	// +optional
	PostgresPassword *SecretKeyRef `json:"postgresPassword,omitempty"`
}

// TraefikSpec configures generation of Traefik resources for Authelia.
// https://www.authelia.com/integration/kubernetes/traefik-ingress/
type TraefikSpec struct {
	// entryPoints are the Traefik entry points the portal IngressRoute listens
	// on. Defaults to ["websecure"].
	// +optional
	EntryPoints []string `json:"entryPoints,omitempty"`
}

// AutheliaDeploymentSpec configures the generated Authelia Deployment.
// +kubebuilder:validation:XValidation:rule="!has(self.volumeClaimTemplate) || (has(self.replicas) && self.replicas == 1)",message="volumeClaimTemplate requires replicas to be 1"
type AutheliaDeploymentSpec struct {
	// replicas is the number of Authelia pods to run.
	// +optional
	// +kubebuilder:default=2
	Replicas *int32 `json:"replicas,omitempty"`

	// image is the Authelia container image.
	// +optional
	// +kubebuilder:default="ghcr.io/authelia/authelia:4"
	Image string `json:"image,omitempty"`

	// imagePullPolicy is the image pull policy for the Authelia container.
	// +optional
	// +kubebuilder:default="IfNotPresent"
	ImagePullPolicy corev1.PullPolicy `json:"imagePullPolicy,omitempty"`

	// resources describes the compute resource requirements for the Authelia
	// container.
	// +optional
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// existingSecret references an existing Secret providing Authelia's core
	// secrets (keys SESSION_ENCRYPTION_KEY, STORAGE_ENCRYPTION_KEY,
	// OIDC_HMAC_SECRET, OIDC_PRIVATE_KEY). It is exposed to the container via
	// envFrom and mounted at /secrets. When unset, the operator generates these
	// secrets into a managed Secret named "<name>-secrets" (generated once and
	// preserved across reconciles).
	// +optional
	ExistingSecret string `json:"existingSecret,omitempty"`

	// volumeClaimTemplate has the operator create and manage a PersistentVolume
	// Claim named "<name>-data" mounted at /data, for persistent state such as a
	// SQLite database. Because the claim is ReadWriteOnce, this is only permitted
	// when replicas is 1. The PVC is retained if the Authelia resource is
	// deleted. When unset, /data uses an emptyDir and does not survive restarts.
	// +optional
	VolumeClaimTemplate *corev1.PersistentVolumeClaimSpec `json:"volumeClaimTemplate,omitempty"`
}

// AutheliaStatus defines the observed state of Authelia.
type AutheliaStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// For Kubernetes API conventions, see:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

	// conditions represent the current state of the Authelia resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// readyReplicas is the number of ready Authelia pods.
	// +optional
	ReadyReplicas int32 `json:"readyReplicas,omitempty"`

	// oidcClients lists the OIDC client IDs currently rendered into the
	// Authelia configuration.
	// +optional
	OIDCClients []string `json:"oidcClients,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=authelias,singular=authelia
// +kubebuilder:printcolumn:name="Replicas",type="integer",JSONPath=".spec.deployment.replicas"
// +kubebuilder:printcolumn:name="Ready",type="integer",JSONPath=".status.readyReplicas"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// Authelia is the Schema for the authelia API
type Authelia struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of Authelia
	// +required
	Spec AutheliaSpec `json:"spec"`

	// status defines the observed state of Authelia
	// +optional
	Status AutheliaStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// AutheliaList contains a list of Authelia
type AutheliaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []Authelia `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Authelia{}, &AutheliaList{})
}
