//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authelia) DeepCopyInto(out *Authelia) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authelia.
func (in *Authelia) DeepCopy() *Authelia {
	if in == nil {
		return nil
	}
	out := new(Authelia)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Authelia) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaDeploymentSpec) DeepCopyInto(out *AutheliaDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SMTPPassword != nil {
		in, out := &in.SMTPPassword, &out.SMTPPassword
		*out = new(bool)
		**out = **in
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaDeploymentSpec.
func (in *AutheliaDeploymentSpec) DeepCopy() *AutheliaDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(AutheliaDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaList) DeepCopyInto(out *AutheliaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Authelia, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaList.
func (in *AutheliaList) DeepCopy() *AutheliaList {
	if in == nil {
		return nil
	}
	out := new(AutheliaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutheliaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaOAuthClient) DeepCopyInto(out *AutheliaOAuthClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaOAuthClient.
func (in *AutheliaOAuthClient) DeepCopy() *AutheliaOAuthClient {
	if in == nil {
		return nil
	}
	out := new(AutheliaOAuthClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutheliaOAuthClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaOAuthClientList) DeepCopyInto(out *AutheliaOAuthClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutheliaOAuthClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaOAuthClientList.
func (in *AutheliaOAuthClientList) DeepCopy() *AutheliaOAuthClientList {
	if in == nil {
		return nil
	}
	out := new(AutheliaOAuthClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutheliaOAuthClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaOAuthClientSpec) DeepCopyInto(out *AutheliaOAuthClientSpec) {
	*out = *in
	out.AutheliaRef = in.AutheliaRef
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaOAuthClientSpec.
func (in *AutheliaOAuthClientSpec) DeepCopy() *AutheliaOAuthClientSpec {
	if in == nil {
		return nil
	}
	out := new(AutheliaOAuthClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaOAuthClientStatus) DeepCopyInto(out *AutheliaOAuthClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaOAuthClientStatus.
func (in *AutheliaOAuthClientStatus) DeepCopy() *AutheliaOAuthClientStatus {
	if in == nil {
		return nil
	}
	out := new(AutheliaOAuthClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaReference) DeepCopyInto(out *AutheliaReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaReference.
func (in *AutheliaReference) DeepCopy() *AutheliaReference {
	if in == nil {
		return nil
	}
	out := new(AutheliaReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaSpec) DeepCopyInto(out *AutheliaSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	if in.AuthenticationBackend != nil {
		in, out := &in.AuthenticationBackend, &out.AuthenticationBackend
		*out = new(AuthenticationBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaSpec.
func (in *AutheliaSpec) DeepCopy() *AutheliaSpec {
	if in == nil {
		return nil
	}
	out := new(AutheliaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutheliaStatus) DeepCopyInto(out *AutheliaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OIDCClients != nil {
		in, out := &in.OIDCClients, &out.OIDCClients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutheliaStatus.
func (in *AutheliaStatus) DeepCopy() *AutheliaStatus {
	if in == nil {
		return nil
	}
	out := new(AutheliaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationBackendSpec) DeepCopyInto(out *AuthenticationBackendSpec) {
	*out = *in
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(FileAuthenticationBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPAuthenticationBackend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationBackendSpec.
func (in *AuthenticationBackendSpec) DeepCopy() *AuthenticationBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileAuthenticationBackend) DeepCopyInto(out *FileAuthenticationBackend) {
	*out = *in
	out.UsersSecret = in.UsersSecret
	if in.Watch != nil {
		in, out := &in.Watch, &out.Watch
		*out = new(bool)
		**out = **in
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(FileSearch)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileAuthenticationBackend.
func (in *FileAuthenticationBackend) DeepCopy() *FileAuthenticationBackend {
	if in == nil {
		return nil
	}
	out := new(FileAuthenticationBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSearch) DeepCopyInto(out *FileSearch) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(bool)
		**out = **in
	}
	if in.CaseInsensitive != nil {
		in, out := &in.CaseInsensitive, &out.CaseInsensitive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSearch.
func (in *FileSearch) DeepCopy() *FileSearch {
	if in == nil {
		return nil
	}
	out := new(FileSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPAuthenticationBackend) DeepCopyInto(out *LDAPAuthenticationBackend) {
	*out = *in
	out.PasswordSecret = in.PasswordSecret
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPAuthenticationBackend.
func (in *LDAPAuthenticationBackend) DeepCopy() *LDAPAuthenticationBackend {
	if in == nil {
		return nil
	}
	out := new(LDAPAuthenticationBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
