name: Docker Build

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  docker-build:
    permissions:
      contents: read
    name: Build controller image
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build controller image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: controller:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
